### ISSUE TITLE
Next button

### ISSUE THREAD

**Issue by rachfop** [tomcam/least-github-pages#1]
Great repo! A lot of great information. This issue relates to how the information is organized. I think it could benefit a lot of beginners if you added a **Next** button. The next button could just link to the next topic in the TOC. 

It might deter your audience to click the back button, search the TOC, and then go to the next topic, so a next button should help.

**Comment by tomcam** [comment]
Excellent idea. Add Top, Back, and Next links to each page. Thank you.
